### PR TITLE
Slash command

### PR DESCRIPTION
**Pull request by johnnyapol**

### CODE REVIEW

**Comment by chrisj1** [comment]
Do you think it would be better to wait until slash commands are supported by discord.py?

**Comment by chrisj1** [comment]
I'll look over this weekend

**Comment by johnnyapol** [comment]
> Do you think it would be better to wait until slash commands are supported by discord.py?

It won't be for a while per the developer. 

My rationale for trying to add support for them has been it eliminates the ping-spam as pinging people in a slash command won't trigger a ping which is why I think its worth trying them out even though its still in beta.

**Comment by chrisj1** [comment]
Good point I want to do some testing before merging. Probably merge this weekend if everything is good.

**Comment by enisaras** [comment]
Will there be no way to letting people know they have been bonoboed with this? Thats kinda half the fun imo.

**Comment by Prasantacharya** [comment]
pr 24 will conflict with this one, will consider again once nextcord is used rather than discord.py

**Pull request closed without merging**
